site_name: Dark Souls Texture Studio
site_description: Documentation for Dark Souls Texture Studio

theme:
  name: material

nav:
  - Home: index.md

  - Getting Started:
    - Installation: installation.md
    - Building from source: building.md

  - User Guide:
    - Introduction: introduction.md
    - Settings: settings.md
    - Exporting Textures: exporting.md
    - Replacing Textures: replacing.md
    - Adding Custom Atlases/Icons: customicons.md
    - Creating a Custom File: customfiles.md
    - High Resolution Textures: hi-res.md
  
  - Supported Games: supported-games.md

  - Other Features: features.md

  - Troubleshooting: troubleshooting.md

  - Advanced:
    - cli: cli.md
    - Console: console.md

  - Contact Me: contact.md